import { useEffect } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const winners = [
  { name: "Adnilsa Trindade Alves", luckyNumber: "46038" },
  { name: "Adnilsa Trindade Alves", luckyNumber: "58708" },
  { name: "Adriana Machado Resende Duelis", luckyNumber: "39166" },
  { name: "Aelço Alves de Paula", luckyNumber: "36494" },
  { name: "Aguilar Teixeira Ribeiro", luckyNumber: "42393" },
  { name: "Aguilar Teixeira Ribeiro", luckyNumber: "66049" },
  { name: "Alayse Aparecida de Melo Morais", luckyNumber: "28625" },
  { name: "Alda Regina Gonzaga e Silva", luckyNumber: "54240" },
  { name: "Aldeir Emílio Gonçalves", luckyNumber: "60630" },
  { name: "Alessandra Aparecida Lourenço Dias de Oliveira", luckyNumber: "66365" },
  { name: "Alexandre Aparecido Fonseca de Gouvea", luckyNumber: "65985" },
  { name: "Alexandre Eduardo da Silva", luckyNumber: "31885" },
  { name: "Alexis Rodrigues da Silva", luckyNumber: "58958" },
  { name: "Alexson Santos Leandro", luckyNumber: "46665" },
  { name: "Alexson Santos Leandro", luckyNumber: "55811" },
  { name: "Alexson Santos Leandro", luckyNumber: "58546" },
  { name: "Alfio Lopes Junior", luckyNumber: "32159" },
  { name: "Alfio Lopes Junior", luckyNumber: "40981" },
  { name: "Alvaro Dias Ferreira", luckyNumber: "56149" },
  { name: "Alvaro Dias Ferreira", luckyNumber: "65707" },
  { name: "Alvaro Dias Ferreira", luckyNumber: "67229" },
  { name: "Amanda Campos", luckyNumber: "64574" },
  { name: "Amanda Machado Alves de Lima", luckyNumber: "34032" },
  { name: "Amezina Alves Ferreira", luckyNumber: "55956" },
  { name: "Amezina Alves Ferreira", luckyNumber: "63849" },
  { name: "Ana Cristina Freesz de Lima", luckyNumber: "31124" },
  { name: "Ana Cristina Freesz de Lima", luckyNumber: "58093" },
  { name: "Ana Cristina Freesz de Lima", luckyNumber: "62384" },
  { name: "Ana d Arc Liberato", luckyNumber: "64418" },
  { name: "Ana Lucia Rodrigues Silva Santos", luckyNumber: "28366" },
  { name: "Ana Maria Moraes de Almeida", luckyNumber: "51132" },
  { name: "Anderson Azevedo Lembi de Carvalho", luckyNumber: "66958" },
  { name: "Anderson Pereira", luckyNumber: "70001" },
  { name: "André Luiz Seixas de Castro", luckyNumber: "47980" },
  { name: "Andréa de Mello Pereira Alves", luckyNumber: "51690" },
  { name: "Andre Souza Rufino", luckyNumber: "38902" },
  { name: "Andrea Patrocínio Dos Santos", luckyNumber: "45434" },
  { name: "Andrea Patrocínio Dos Santos", luckyNumber: "53978" },
  { name: "Angela Aparecida Loreto da Silva", luckyNumber: "24678" },
  { name: "Angela Maria Pereira da Silva", luckyNumber: "43287" },
  { name: "Angelica Gabriele Moreira da Silva", luckyNumber: "37711" },
  { name: "Angelica Gabriele Moreira da Silva", luckyNumber: "66432" },
  { name: "Anna Cláudia Souza Lemos", luckyNumber: "34778" },
  { name: "Antônio Carlos Teixeira", luckyNumber: "62777" },
  { name: "Antao Cota de Oliveira", luckyNumber: "37812" },
  { name: "Antonio Carlos Ferreira Macedo", luckyNumber: "45908" },
  { name: "Antonio Carlos Ferreira Macedo", luckyNumber: "61917" },
  { name: "Arison Paulo de Oliveira Arison", luckyNumber: "49493" },
  { name: "Arlene Alessandra de Oliveira", luckyNumber: "38587" },
  { name: "Arlene Alessandra de Oliveira", luckyNumber: "48706" },
  { name: "Arlete Antunes de Moraes", luckyNumber: "52355" },
  { name: "Arthur Fortes Moreno Fernandes", luckyNumber: "28703" },
  { name: "Atanicio Viana de Souza", luckyNumber: "53782" },
  { name: "Ayrton Duarte Dalla", luckyNumber: "27430" },
  { name: "Breno Jardim Silva", luckyNumber: "68136" },
  { name: "Camila Augusta Vieira", luckyNumber: "66389" },
  { name: "Carlos Alberto de Sousa", luckyNumber: "37788" },
  { name: "Carlos Cesar Ferreira", luckyNumber: "60595" },
  { name: "Carlos Eustáquio de Oliveira", luckyNumber: "37299" },
  { name: "Carlos Henrique Lucchesi Batista", luckyNumber: "47543" },
  { name: "Carmem Deusane Fialho de Melo", luckyNumber: "49134" },
  { name: "Carmem Miranda Rios Bretas", luckyNumber: "60748" },
  { name: "Catarina de Paiva Santos", luckyNumber: "63685" },
  { name: "Catarina de Paiva Santos", luckyNumber: "65692" },
  { name: "Celia Schaper Bizzotto", luckyNumber: "25190" },
  { name: "Celia Schaper Bizzotto", luckyNumber: "51655" },
  { name: "Cheila Simplicio", luckyNumber: "62514" },
  { name: "Chesma Onofre da Cruz", luckyNumber: "29867" },
  { name: "Chesma Onofre da Cruz", luckyNumber: "31731" },
  { name: "Chesma Onofre da Cruz", luckyNumber: "64558" },
  { name: "Cibele Dos Santos Silva Dvale", luckyNumber: "54303" },
  { name: "Cibele Souza Soares", luckyNumber: "26467" },
  { name: "Cibele Souza Soares", luckyNumber: "51872" },
  { name: "Cinthia Alexandra Pereira Rodrigues", luckyNumber: "65998" },
  { name: "Cirlene Maria Martins Andrade", luckyNumber: "38446" },
  { name: "Cláudia Zille Pereira Vieira", luckyNumber: "33365" },
  { name: "Cláudia Zille Pereira Vieira", luckyNumber: "57705" },
  { name: "Cláudia Zille Pereira Vieira", luckyNumber: "60663" },
  { name: "Cláudio Alexandre Pereira", luckyNumber: "35560" },
  { name: "Claudia Bernadete Vaz Lopes", luckyNumber: "65381" },
  { name: "Claudia Fernandes da Costa", luckyNumber: "40942" },
  { name: "Claudia Helena Magalhães Nunes", luckyNumber: "45149" },
  { name: "Claudia Irene Martins Fernandes", luckyNumber: "65908" },
  { name: "Claudinei Marcos Gualberto", luckyNumber: "64692" },
  { name: "Claudiney da Silva Soares", luckyNumber: "48701" },
  { name: "Clayton Teixeira de Araujo", luckyNumber: "41572" },
  { name: "Cleber Lima Dos Santos", luckyNumber: "30359" },
  { name: "Cleude Eloisa Alves Pantolfo", luckyNumber: "41723" },
  { name: "Cleude Eloisa Alves Pantolfo", luckyNumber: "57611" },
  { name: "Cosme Damião de Azevedo", luckyNumber: "23983" },
  { name: "Cristiano Juvenal da Silva", luckyNumber: "39102" },
  { name: "Cristiano Juvenal da Silva", luckyNumber: "50854" },
  { name: "Cristina Aparecida Barbosa", luckyNumber: "60606" },
  { name: "Cristina Aparecida Barbosa", luckyNumber: "62322" },
  { name: "Cristina Melo Ferreti de Souza", luckyNumber: "53946" },
  { name: "Cristina Oliveira Carvalho", luckyNumber: "51510" },
  { name: "Cristina Pedrosa Braga", luckyNumber: "66228" },
  { name: "Daiani da Rocha", luckyNumber: "35402" },
  { name: "Daiani da Rocha", luckyNumber: "36833" },
  { name: "Daiani da Rocha", luckyNumber: "38564" },
  { name: "Daiani da Rocha", luckyNumber: "52578" },
  { name: "Daiani da Rocha", luckyNumber: "55819" },
  { name: "Daiani da Rocha", luckyNumber: "57762" },
  { name: "Daiani da Rocha", luckyNumber: "60761" },
  { name: "Daiani da Rocha", luckyNumber: "62394" },
  { name: "Daiani da Rocha", luckyNumber: "67856" },
  { name: "Dalton Francileno Diniz", luckyNumber: "38749" },
  { name: "Dalton Francileno Diniz", luckyNumber: "62026" },
  { name: "Daniela de Melo Belasque", luckyNumber: "32581" },
  { name: "Daniela de Melo Belasque", luckyNumber: "57271" },
  { name: "Daniela Marques Sanches", luckyNumber: "28215" },
  { name: "Daniela Marques Sanches", luckyNumber: "45442" },
  { name: "Daniela Xavier Santos", luckyNumber: "37554" },
  { name: "Daniela Xavier Santos", luckyNumber: "69546" },
  { name: "Dazany Gisele Barbara Mendes", luckyNumber: "31939" },
  { name: "Deborah Christina Lopes Hoffmam", luckyNumber: "32071" },
  { name: "Deborah Christina Lopes Hoffmam", luckyNumber: "48143" },
  { name: "Dejair David Salgueiro de Oliveira", luckyNumber: "61600" },
  { name: "Denise Lichter", luckyNumber: "26872" },
  { name: "Diego Jordan de Oliveira Valentino", luckyNumber: "42955" },
  { name: "Diogo Ladislau Santos da Silva", luckyNumber: "25793" },
  { name: "Diogo Ladislau Santos da Silva", luckyNumber: "41500" },
  { name: "Dirceu de Oliveira Vilela", luckyNumber: "38805" },
  { name: "Douglas da Costa Gomes", luckyNumber: "59309" },
  { name: "Douglas Vitor Cezario", luckyNumber: "27471" },
  { name: "Edgard Lagrotta Pittella", luckyNumber: "32900" },
  { name: "Edimar Canuto Carneiro", luckyNumber: "29232" },
  { name: "Edivaldo da Silva", luckyNumber: "41002" },
  { name: "Edna Firmina Costa Alvim", luckyNumber: "33328" },
  { name: "Edna Firmina Costa Alvim", luckyNumber: "50201" },
  { name: "Edson Silva Pinto", luckyNumber: "42158" },
  { name: "Eduarda Silva", luckyNumber: "28407" },
  { name: "Eduardo Schirmer", luckyNumber: "33581" },
  { name: "Eduardo Schirmer", luckyNumber: "46960" },
  { name: "Eduardo Schirmer", luckyNumber: "49148" },
  { name: "Edvaldo Vitor Lopes", luckyNumber: "27172" },
  { name: "Eládio Martins Dos Santos", luckyNumber: "51735" },
  { name: "Elbert Reis Marques", luckyNumber: "24556" },
  { name: "Eldem Francisco Chagas", luckyNumber: "29909" },
  { name: "Eliana Grassi Ferreira de Abreu", luckyNumber: "46637" },
  { name: "Eliene d p Petzold", luckyNumber: "55735" },
  { name: "Elisângela Marcia da Cunha Queiroga", luckyNumber: "57486" },
  { name: "Elisangela Martins Santana", luckyNumber: "39504" },
  { name: "Elizabete Gomes Fernandes", luckyNumber: "23799" },
  { name: "Elton Gonçalves Brandão", luckyNumber: "68830" },
  { name: "Emanuelle s Faria", luckyNumber: "32869" },
  { name: "Emanuelle s Faria", luckyNumber: "38950" },
  { name: "Emanuelle s Faria", luckyNumber: "68349" },
  { name: "Érica de Oliveira Moraes Silva", luckyNumber: "42933" },
  { name: "Ester Maria Penido Iassuda", luckyNumber: "64304" },
  { name: "Evânia Evangelista da Silva Resende", luckyNumber: "57060" },
  { name: "Evando Araújo da Silva", luckyNumber: "23927" },
  { name: "Ewerton Flavio Vieira", luckyNumber: "57394" },
  { name: "Fabiano Brazão", luckyNumber: "64189" },
  { name: "Fernanda Bertollo Limongi", luckyNumber: "60531" },
  { name: "Fernanda Cristina Graciano da Silva", luckyNumber: "60548" },
  { name: "Fernanda Cristina Graciano da Silva", luckyNumber: "62165" },
  { name: "Fernanda Ferreira Camargos", luckyNumber: "40622" },
  { name: "Fernando Cruz Laender", luckyNumber: "67289" },
  { name: "Fernando e r Gomes", luckyNumber: "44737" },
  { name: "Fernando José Gonçalves de Souza", luckyNumber: "34943" },
  { name: "Fernando Ladeira Aragao", luckyNumber: "51857" },
  { name: "Fernando Ladeira Aragao", luckyNumber: "52413" },
  { name: "Filomena Maria de Oliveira", luckyNumber: "58660" },
  { name: "Flávia Belloni Rocha Daguer", luckyNumber: "39176" },
  { name: "Flávia Belloni Rocha Daguer", luckyNumber: "48445" },
  { name: "Flávio Donizete da Silva", luckyNumber: "61836" },
  { name: "Flavio Batista Dos Santos", luckyNumber: "51056" },
  { name: "Francisco Aloisio Miranda", luckyNumber: "53044" },
  { name: "Francisco Aloisio Miranda", luckyNumber: "59588" },
  { name: "Francisco de Melo", luckyNumber: "49261" },
  { name: "Francisco de Oliveira Matias", luckyNumber: "32340" },
  { name: "Francisco Gonçalves Filho", luckyNumber: "35264" },
  { name: "Francisco Gonçalves Filho", luckyNumber: "50095" },
  { name: "Frederico Almeida Barbosa", luckyNumber: "59822" },
  { name: "Frederico Valério Rodrigues", luckyNumber: "60295" },
  { name: "Gabriel Aparecido Ferreira", luckyNumber: "24723" },
  { name: "Gabriela Queiroz Altino Silva", luckyNumber: "24080" },
  { name: "Gabriela Vilela de Mattos", luckyNumber: "36575" },
  { name: "Gabriela Vilela de Mattos", luckyNumber: "39451" },
  { name: "Geralda Isa da Silva", luckyNumber: "44087" },
  { name: "Geraldo Dias Pena", luckyNumber: "29194" },
  { name: "Geraldo Guimarães Vieira Dos Santos", luckyNumber: "28266" },
  { name: "Geraldo Tarcísio da Cunha", luckyNumber: "60166" },
  { name: "Gil Pereira Guimarães", luckyNumber: "66587" },
  { name: "Guilherme de Oliveira", luckyNumber: "52458" },
  { name: "Guilherme Zordan", luckyNumber: "69503" },
  { name: "Hannah Karolina Fernandes de Oliveira", luckyNumber: "63372" },
  { name: "Helder Savio de Figueiredo Silva", luckyNumber: "68341" },
  { name: "Heros Lobato", luckyNumber: "64614" },
  { name: "Igor de Jesus Martins", luckyNumber: "66955" },
  { name: "Ilma Arantes Mendonça", luckyNumber: "41556" },
  { name: "Ilma Arantes Mendonça", luckyNumber: "49783" },
  { name: "Isadora Priscila Lima Ribeiro", luckyNumber: "38964" },
  { name: "Isadora Priscila Lima Ribeiro", luckyNumber: "58320" },
  { name: "Isadora Priscila Lima Ribeiro", luckyNumber: "60463" },
  { name: "Isadora Priscila Lima Ribeiro", luckyNumber: "67045" },
  { name: "Ivan Duque de Paiva Filho", luckyNumber: "37998" },
  { name: "Ivan Duque de Paiva Filho", luckyNumber: "39572" },
  { name: "Ivan Duque de Paiva Filho", luckyNumber: "65783" },
  { name: "Ivaneide Santos Silva", luckyNumber: "65458" },
  { name: "Ivone Arruda de Oliveira", luckyNumber: "65097" },
  { name: "Izaias Mendes Dos Anjos", luckyNumber: "31906" },
  { name: "Izaias Mendes Dos Anjos", luckyNumber: "48152" },
  { name: "Izaias Mendes Dos Anjos", luckyNumber: "64667" },
  { name: "Jacinto Rodrigues", luckyNumber: "34415" },
  { name: "Jacinto Rodrigues", luckyNumber: "63529" },
  { name: "Jailson Moreira Dos Santos", luckyNumber: "38032" },
  { name: "Janet Lisboa Ribeiro Melo", luckyNumber: "48417" },
  { name: "Júlio Roberto Alves Dos Santos", luckyNumber: "42824" },
  { name: "Júlio Roberto Alves Dos Santos", luckyNumber: "60261" },
  { name: "Jaqueline Alves de Souza", luckyNumber: "24260" },
  { name: "Jayme Afonso Lisboa", luckyNumber: "43104" },
  { name: "Jessica Azevedo Ferreira", luckyNumber: "36443" },
  { name: "Jessica Griebeler Martins Villas Boas", luckyNumber: "53885" },
  { name: "Jessica Griebeler Martins Villas Boas", luckyNumber: "66016" },
  { name: "Jessica Griebeler Martins Villas Boas", luckyNumber: "68834" },
  { name: "João Pinto Papa", luckyNumber: "33923" },
  { name: "Joao a c v Pereira", luckyNumber: "24318" },
  { name: "Joao a c v Pereira", luckyNumber: "47532" },
  { name: "Joao Eduardo de Rezende Dantas", luckyNumber: "39943" },
  { name: "Joelma Laurindo Zacarias", luckyNumber: "33185" },
  { name: "Joice Dias Dos Santos", luckyNumber: "39084" },
  { name: "Jonas Rodrigues Pereira", luckyNumber: "32689" },
  { name: "Jonatas Teixeira da Rocha", luckyNumber: "31624" },
  { name: "Jonatas Vieira Goncalves", luckyNumber: "37839" },
  { name: "Jorge Alexandre Alves", luckyNumber: "52044" },
  { name: "Jorge Eustaquio de Oliveira", luckyNumber: "61385" },
  { name: "Jorge Ibrahin Abbud", luckyNumber: "26909" },
  { name: "Jorge Ibrahin Abbud", luckyNumber: "58455" },
  { name: "Jorge Ibrahin Abbud", luckyNumber: "67850" },
  { name: "Jorismar Bastos Ferreira", luckyNumber: "62354" },
  { name: "José Ferreira Dos Santos", luckyNumber: "59329" },
  { name: "José Perpétuo de Rezende Júnior", luckyNumber: "37074" },
  { name: "José Rogério Ferreira Marques", luckyNumber: "54441" },
  { name: "Jose Dos Reis Ricardo", luckyNumber: "41557" },
  { name: "Jose Maria Dos Reis Almeida", luckyNumber: "35253" },
  { name: "Jose Maria Dos Reis Almeida", luckyNumber: "37388" },
  { name: "Jouber Carlos de Lacerda", luckyNumber: "53286" },
  { name: "Jouber Carlos de Lacerda", luckyNumber: "58558" },
  { name: "Julia Coelho Macedo", luckyNumber: "27749" },
  { name: "Julio Silva Nunes", luckyNumber: "35448" },
  { name: "Junio Jaques Dos Santos", luckyNumber: "38239" },
  { name: "Karen Aline da Silva Retuci", luckyNumber: "57042" },
  { name: "Katia Bernardes Resende Dias", luckyNumber: "38367" },
  { name: "Kelli Fernanda da Silva", luckyNumber: "26436" },
  { name: "Kelli Fernanda da Silva", luckyNumber: "40630" },
  { name: "Kelly Karoliny Vieira Chaves", luckyNumber: "63976" },
  { name: "Keyla Rodrigues Dos Santos", luckyNumber: "39192" },
  { name: "Keyla Rodrigues Dos Santos", luckyNumber: "39238" },
  { name: "Lais Vieira da Cruz", luckyNumber: "60807" },
  { name: "Laura de Paula Moreira Frattezi", luckyNumber: "44075" },
  { name: "Leonardo Braga de Assis", luckyNumber: "40989" },
  { name: "Leonardo Braga de Assis", luckyNumber: "60775" },
  { name: "Letícia Cunha", luckyNumber: "34366" },
  { name: "Libiane Gonçalves Campos", luckyNumber: "39466" },
  { name: "Liliane Figueiredo Lamego", luckyNumber: "28084" },
  { name: "Loruama Ramos", luckyNumber: "56632" },
  { name: "Lourdes Maria Vieira", luckyNumber: "49354" },
  { name: "Luc Jean Philippe Nader", luckyNumber: "33683" },
  { name: "Lucas Azevedo Paulino", luckyNumber: "68643" },
  { name: "Lucas da Rocha Silva", luckyNumber: "61980" },
  { name: "Luciana Otoni Nascimento", luckyNumber: "62198" },
  { name: "Luciano Rodrigues Dos Santos", luckyNumber: "35643" },
  { name: "Lucimar Pereira Cavalcanti", luckyNumber: "66595" },
  { name: "Luis Otavio Correa Camara", luckyNumber: "26196" },
  { name: "Luis Otavio Correa Camara", luckyNumber: "45178" },
  { name: "Luiz Carlos Rodrigues Alvarenga", luckyNumber: "33984" },
  { name: "Luiz Gonzaga Toledo Pereira", luckyNumber: "28464" },
  { name: "Márcia Cavalcanti Moreira", luckyNumber: "67301" },
  { name: "Márcia Machado Barbosa Souza", luckyNumber: "53839" },
  { name: "Mário Eugênio Pereira Dos Santos", luckyNumber: "53812" },
  { name: "Mário Eugênio Pereira Dos Santos", luckyNumber: "55911" },
  { name: "Mário Eugênio Pereira Dos Santos", luckyNumber: "57944" },
  { name: "Mário Eugênio Pereira Dos Santos", luckyNumber: "59363" },
  { name: "Mailde Ribeiro", luckyNumber: "35935" },
  { name: "Mara Das Dores de Souza Batista", luckyNumber: "55756" },
  { name: "Marília Pereira da Silva", luckyNumber: "58786" },
  { name: "Marcelo Neves Andrade Brito", luckyNumber: "34575" },
  { name: "Marco Aurélio Penzim", luckyNumber: "33097" },
  { name: "Marco Aurélio Penzim", luckyNumber: "42473" },
  { name: "Marco Túlio Silva Abdala", luckyNumber: "36779" },
  { name: "Marcos da Silva Vieira", luckyNumber: "59725" },
  { name: "Marcos Filipe da Silveira Amorim", luckyNumber: "24559" },
  { name: "Marcos Filipe da Silveira Amorim", luckyNumber: "67605" },
  { name: "Marcos Jorge Alves Gemaque", luckyNumber: "42173" },
  { name: "Marcos Quintino Dos Santos", luckyNumber: "60911" },
  { name: "Marcus Paulo de Moura Aguiar", luckyNumber: "63639" },
  { name: "Maria Ângela Cabral Toscano Barreto", luckyNumber: "27482" },
  { name: "Maria Aparecida de Oliveira", luckyNumber: "46551" },
  { name: "Maria Aparecida de Oliveira Salustiano", luckyNumber: "47969" },
  { name: "Maria Auxiliadora Gomes", luckyNumber: "36825" },
  { name: "Maria da Glória Machado Givisiez", luckyNumber: "39654" },
  { name: "Maria Das Graças de Souza", luckyNumber: "63306" },
  { name: "Maria Das Graças Duarte", luckyNumber: "48719" },
  { name: "Maria Das Graças Duarte", luckyNumber: "59763" },
  { name: "Maria Das Graças Duarte", luckyNumber: "63594" },
  { name: "Maria de Fátima Assis", luckyNumber: "26621" },
  { name: "Maria de Fátima Assis", luckyNumber: "29251" },
  { name: "Maria de Fátima Rodrigues", luckyNumber: "47590" },
  { name: "Maria Eduarda de Moura Barcelos", luckyNumber: "47986" },
  { name: "Maria Eduarda de Moura Barcelos", luckyNumber: "64772" },
  { name: "Maria Elizabeth Viana", luckyNumber: "43021" },
  { name: "Maria Elizabeth Viana", luckyNumber: "62376" },
  { name: "Maria Guiomar da Costa Silva", luckyNumber: "58191" },
  { name: "Maria Luiza Reis Silva", luckyNumber: "27534" },
  { name: "Maria Luzia Ferreira Costa", luckyNumber: "60945" },
  { name: "Maria Regina Harumi Taba", luckyNumber: "23849" },
  { name: "Maria Solange Pinto", luckyNumber: "29520" },
  { name: "Maria Zilda Bibiano Oliveira Souza", luckyNumber: "38600" },
  { name: "Maria Zilda Bibiano Oliveira Souza", luckyNumber: "38823" },
  { name: "Mariza Freitas Duarte", luckyNumber: "31678" },
  { name: "Marli Keller", luckyNumber: "45345" },
  { name: "Marlon Rangel Alves Almeida", luckyNumber: "25911" },
  { name: "Marlon Rangel Alves Almeida", luckyNumber: "26951" },
  { name: "Marlon Rangel Alves Almeida", luckyNumber: "55250" },
  { name: "Marlon Rangel Alves Almeida", luckyNumber: "58103" },
  { name: "Matildes Souza de Almeida", luckyNumber: "30550" },
  { name: "Maura Ferreira Lima da Silva Dias", luckyNumber: "24466" },
  { name: "Mauricio Moreira Dos Santos", luckyNumber: "30425" },
  { name: "Mauricio Moreira Dos Santos", luckyNumber: "36350" },
  { name: "Mauro Henrique Dias da Cruz", luckyNumber: "60835" },
  { name: "Max França Lommez", luckyNumber: "28217" },
  { name: "Max França Lommez", luckyNumber: "49807" },
  { name: "Michael Avelino de Carvalho", luckyNumber: "23918" },
  { name: "Mirtes Eliane de Oliveira", luckyNumber: "41021" },
  { name: "Moacyr Ferreira", luckyNumber: "37113" },
  { name: "Moacyr Ferreira", luckyNumber: "58917" },
  { name: "Moacyr Ferreira", luckyNumber: "60674" },
  { name: "Moacyr Ferreira", luckyNumber: "69490" },
  { name: "Monica Soares Verissimo", luckyNumber: "60060" },
  { name: "Muller Alves Costa", luckyNumber: "61907" },
  { name: "Nélio Ferreira da Silva", luckyNumber: "35648" },
  { name: "Nadier Jose Dos Santos Filho", luckyNumber: "39719" },
  { name: "Naly Medeiros Soares", luckyNumber: "55330" },
  { name: "Nardele Teles Duarte", luckyNumber: "53687" },
  { name: "Nardele Teles Duarte", luckyNumber: "54658" },
  { name: "Natália Francini de Sousa", luckyNumber: "42558" },
  { name: "Natalina Rodrigues Vieira", luckyNumber: "46613" },
  { name: "Nathalia Morandini", luckyNumber: "48740" },
  { name: "Nery Roberto Invernizzi Pope", luckyNumber: "60225" },
  { name: "Neusa Cândida de Faria Dias Pereira", luckyNumber: "31799" },
  { name: "Nilo Campos", luckyNumber: "33704" },
  { name: "Nilza Maria de Oliveira", luckyNumber: "63622" },
  { name: "Nivia Pereira Pardinho", luckyNumber: "54795" },
  { name: "Osmar César da Silva", luckyNumber: "27638" },
  { name: "Othon Morais Bomfim", luckyNumber: "36027" },
  { name: "Paloma Natalina Ribeiro Silva", luckyNumber: "43413" },
  { name: "Paloma Natalina Ribeiro Silva", luckyNumber: "59352" },
  { name: "Pamela Christine Dutra", luckyNumber: "35101" },
  { name: "Patrícia Antônia Gomes de Assis", luckyNumber: "56347" },
  { name: "Patrícia Aparecida Luiz", luckyNumber: "31039" },
  { name: "Patrícia Aparecida Pimenta Pereira", luckyNumber: "49490" },
  { name: "Patricia Carvalho Calegar", luckyNumber: "45866" },
  { name: "Patrik Diniz da Silva", luckyNumber: "65455" },
  { name: "Paula Aparecida Pereira Louzada", luckyNumber: "41844" },
  { name: "Paula Dias Lamarca", luckyNumber: "28476" },
  { name: "Paula Dias Lamarca", luckyNumber: "39618" },
  { name: "Paulo Fernando Andrade", luckyNumber: "27465" },
  { name: "Paulo Renato Pereira", luckyNumber: "56685" },
  { name: "Paulo Ricardo da Silva", luckyNumber: "37222" },
  { name: "Pedro Guilherme Mendonca Silva e Souza", luckyNumber: "30118" },
  { name: "Pedro Henrique Nogueira Dos Santos", luckyNumber: "65975" },
  { name: "Priscila Avelino Ferreira", luckyNumber: "51099" },
  { name: "Rômulo Ramos Santos Ferreira", luckyNumber: "35884" },
  { name: "Rachel Della Croce Santos", luckyNumber: "49072" },
  { name: "Rainá Aparecida de Oliveira Santos", luckyNumber: "23883" },
  { name: "Rainá Aparecida de Oliveira Santos", luckyNumber: "64856" },
  { name: "Raphael Guedes de Oliveira Nascimento", luckyNumber: "33298" },
  { name: "Raphael Guedes de Oliveira Nascimento", luckyNumber: "60969" },
  { name: "Raphael Pereira Dos Santos", luckyNumber: "69923" },
  { name: "Regiane Pereira Brandao", luckyNumber: "27780" },
  { name: "Regina Celia Luiz da Silva", luckyNumber: "56349" },
  { name: "Regina Furtado Ribeiro", luckyNumber: "48650" },
  { name: "Regina Furtado Ribeiro", luckyNumber: "66418" },
  { name: "Rejane Aparecida Vieira", luckyNumber: "27709" },
  { name: "Rejane Aparecida Vieira", luckyNumber: "45158" },
  { name: "Rejane Aparecida Vieira", luckyNumber: "61357" },
  { name: "Rejane Piau e Silva", luckyNumber: "38333" },
  { name: "Rejane Piau e Silva", luckyNumber: "58425" },
  { name: "Rejane Santos Silva", luckyNumber: "35072" },
  { name: "Renan Eduardo Ferreira Pinto", luckyNumber: "58588" },
  { name: "Renata Almeida Murta", luckyNumber: "62294" },
  { name: "Renata Aparecida Diniz", luckyNumber: "44499" },
  { name: "Renata Cristina de Oliveira Sampaio Rosaes", luckyNumber: "65434" },
  { name: "Renato Alevato Escobar de Paula", luckyNumber: "31286" },
  { name: "Renato Alevato Escobar de Paula", luckyNumber: "47149" },
  { name: "Renato Alevato Escobar de Paula", luckyNumber: "63485" },
  { name: "Renato Alevato Escobar de Paula", luckyNumber: "67217" },
  { name: "Renato Alevato Escobar de Paula", luckyNumber: "70206" },
  { name: "Renato de Assis Carvalho", luckyNumber: "26535" },
  { name: "Renilson Geraldo de Oliveira", luckyNumber: "32364" },
  { name: "Renilson Geraldo de Oliveira", luckyNumber: "44270" },
  { name: "Ricardo Vilela Cecílio", luckyNumber: "25170" },
  { name: "Ricardo Vilela Cecílio", luckyNumber: "34947" },
  { name: "Roberto Silva Batista", luckyNumber: "39828" },
  { name: "Roberto Silva Batista", luckyNumber: "45541" },
  { name: "Robertson Eugênio", luckyNumber: "45259" },
  { name: "Robertson Eugênio", luckyNumber: "45291" },
  { name: "Rodrigo Almeida Guilherme", luckyNumber: "39307" },
  { name: "Rodrigo Almeida Guilherme", luckyNumber: "56509" },
  { name: "Rodrigo Almeida Guilherme", luckyNumber: "69356" },
  { name: "Rogerio de Medeiros Tancredo", luckyNumber: "30915" },
  { name: "Rogerio de Medeiros Tancredo", luckyNumber: "33350" },
  { name: "Rogerio de Medeiros Tancredo", luckyNumber: "68079" },
  { name: "Romualdo Moraes", luckyNumber: "27938" },
  { name: "Romualdo Moraes", luckyNumber: "38739" },
  { name: "Rosângela Aparecida Santos", luckyNumber: "31223" },
  { name: "Rosângela Aparecida Santos", luckyNumber: "50950" },
  { name: "Rosângela Aparecida Santos", luckyNumber: "51172" },
  { name: "Rosângela Aparecida Santos", luckyNumber: "53429" },
  { name: "Rosângela Aparecida Santos", luckyNumber: "61418" },
  { name: "Rosângela de Matos Santos", luckyNumber: "54098" },
  { name: "Rosangela Dos Santos Detours", luckyNumber: "38254" },
  { name: "Rosangela Dos Santos Detours", luckyNumber: "47101" },
  { name: "Rosangela Dos Santos Detours", luckyNumber: "67062" },
  { name: "Rosangela Dos Santos Detours", luckyNumber: "69573" },
  { name: "Rosiane Alves Pereira", luckyNumber: "37738" },
  { name: "Rosiane Flávia Baeta", luckyNumber: "57998" },
  { name: "Rosiane Flávia Baeta", luckyNumber: "63553" },
  { name: "Rosilene da Silva Ferreira", luckyNumber: "50451" },
  { name: "Rosilene Dias Ramos", luckyNumber: "59798" },
  { name: "Rosilene Dias Ramos", luckyNumber: "67120" },
  { name: "Rubens Souza de Oliveira", luckyNumber: "47860" },
  { name: "Rubens Souza de Oliveira", luckyNumber: "57049" },
  { name: "Sônia Regina da Silva Reis", luckyNumber: "53745" },
  { name: "Sérgio González Cunha", luckyNumber: "38047" },
  { name: "Sérgio González Cunha", luckyNumber: "63957" },
  { name: "Sérgio William Nascimento Pinto", luckyNumber: "58492" },
  { name: "Sandra de Oliveira Bernardes", luckyNumber: "69499" },
  { name: "Sandro Conceição Rodrigues", luckyNumber: "56137" },
  { name: "Schendla Avila Amaral Magalhaes", luckyNumber: "54194" },
  { name: "Sebastiao Antonio de Freitas", luckyNumber: "43385" },
  { name: "Sheila Assis", luckyNumber: "26848" },
  { name: "Sheila Assis", luckyNumber: "35913" },
  { name: "Sheila Assis", luckyNumber: "48060" },
  { name: "Sidinia Elian Zaidan", luckyNumber: "38424" },
  { name: "Silvio de Almeida Filho", luckyNumber: "43555" },
  { name: "Silvio de Almeida Filho", luckyNumber: "57625" },
  { name: "Sirlene Lina Dos Santos Cerqueira", luckyNumber: "35489" },
  { name: "Solange Lopes de Miranda Fernandes", luckyNumber: "57821" },
  { name: "Solange Siqueira da Silva", luckyNumber: "54987" },
  { name: "Stefanie Lais b de Paula Nunes", luckyNumber: "30166" },
  { name: "Stefanie Lais b de Paula Nunes", luckyNumber: "52981" },
  { name: "Suellen Paulon de Andrade", luckyNumber: "31057" },
  { name: "Suely Maria Marques Pena", luckyNumber: "26923" },
  { name: "Suely Maria Marques Pena", luckyNumber: "54929" },
  { name: "Sylvio Roberto Coutinho de Mattos", luckyNumber: "38559" },
  { name: "Tadeu Vilanova Monteiro de Barros", luckyNumber: "29369" },
  { name: "Tadeu Vilanova Monteiro de Barros", luckyNumber: "64023" },
  { name: "Tamiris Santos", luckyNumber: "41564" },
  { name: "Tania Maia", luckyNumber: "33269" },
  { name: "Tania Rodrigues Dos Santos", luckyNumber: "62571" },
  { name: "Tania Rodrigues Dos Santos", luckyNumber: "63006" },
  { name: "Tatiana Alecrim Madeira", luckyNumber: "33187" },
  { name: "Tatiana Silva Martins", luckyNumber: "46121" },
  { name: "Tereza Cristina de Azevedo Silveira", luckyNumber: "47970" },
  { name: "Tereza Cristina de Azevedo Silveira", luckyNumber: "63932" },
  { name: "Thaianne Almeida Coimbra", luckyNumber: "66348" },
  { name: "Thais Regina Roscoe Ferreira", luckyNumber: "43222" },
  { name: "Thalyson de Souza Mendes", luckyNumber: "32465" },
  { name: "Thereza de Lamare Franco Netto", luckyNumber: "24673" },
  { name: "Thiago Rafael Dos Santos", luckyNumber: "34080" },
  { name: "Thiago Rafael Dos Santos", luckyNumber: "36198" },
  { name: "Thiago Rafael Dos Santos", luckyNumber: "64815" },
  { name: "Thiago Santos da Silva", luckyNumber: "52914" },
  { name: "Thiago Santos da Silva", luckyNumber: "56697" },
  { name: "Vânia Maria", luckyNumber: "24967" },
  { name: "Vânia Pereira de Paiva", luckyNumber: "44566" },
  { name: "Valdecy de Fátima Moreira Santos", luckyNumber: "67113" },
  { name: "Valdemar de Freitas Sobrinho", luckyNumber: "31282" },
  { name: "Valeria Goncalves Magalhaes de Oliveira", luckyNumber: "60457" },
  { name: "Valtair Alves Miranda", luckyNumber: "33701" },
  { name: "Vanderlei Passos Pereira", luckyNumber: "35047" },
  { name: "Vanessa Cristina Martins Gonçalves", luckyNumber: "52219" },
  { name: "Vanessa Luiza da Assunção", luckyNumber: "64853" },
  { name: "Vania Regina Alves", luckyNumber: "38323" },
  { name: "Vanusa Ramos Pereira", luckyNumber: "37409" },
  { name: "Vera Lucia Gomes de Souza", luckyNumber: "58846" },
  { name: "Vera Maria Bicalho da Rocha", luckyNumber: "36718" },
  { name: "Vera Maria Bicalho da Rocha", luckyNumber: "48138" },
  { name: "Vera Maria Bicalho da Rocha", luckyNumber: "60464" },
  { name: "Vilmar Gomes Santos", luckyNumber: "37420" },
  { name: "Vitalina Delfina Dos Santos", luckyNumber: "31676" },
  { name: "Vitoria Rodrigues Garcia", luckyNumber: "52867" },
  { name: "Vitoria Rodrigues Garcia", luckyNumber: "62364" },
  { name: "Vitoria Rodrigues Garcia", luckyNumber: "66528" },
  { name: "Viviane Moreira Adame", luckyNumber: "58839" },
  { name: "Wadison Rodrigues de Araújo", luckyNumber: "34411" },
  { name: "Wadison Rodrigues de Araújo", luckyNumber: "36030" },
  { name: "Wagner Gonçalves Campos", luckyNumber: "24026" },
  { name: "Wagner Murilo Horta", luckyNumber: "43694" },
  { name: "Wander Duarte Batista", luckyNumber: "25303" },
  { name: "Wander Duarte Batista", luckyNumber: "30438" },
  { name: "Wander Duarte Batista", luckyNumber: "49950" },
  { name: "Wanderléia Rodrigues Dos Santos Cruz", luckyNumber: "65981" },
  { name: "William de Oliveira", luckyNumber: "36900" },
  { name: "Wilson Vaz da Fonseca", luckyNumber: "34438" },
  { name: "Zélia Gomes Caires da Silva", luckyNumber: "26904" },
  { name: "Zélia Gomes Caires da Silva", luckyNumber: "59836" },
];

const Ganhadores = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen">
      <Header />

      <main className="bg-primary">
        <div className="container mx-auto px-4 py-16">
          <div className="text-center space-y-6 mb-12">
            <h1 className="text-5xl md:text-6xl font-black text-secondary">Ganhadores</h1>
          </div>

          <div className="max-w-6xl mx-auto bg-background rounded-3xl p-6 md:p-12 shadow-2xl">
            <div className="text-center mb-8 space-y-4">
              <h2 className="text-2xl md:text-3xl font-black text-foreground">Parabéns aos ganhadores!</h2>
              <p className="text-sm md:text-base text-foreground/80 max-w-3xl mx-auto">
                Nossa equipe entrará em contato com todos os ganhadores até o dia 19 de Dezembro de 2025, com as
                orientações completas para a retirada do prêmio.{" "}
                <span className="text-red-600 font-semibold">(Aguardem o nosso contato)</span>
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              {winners.map((winner, index) => (
                <div
                  key={index}
                  className="bg-primary/5 border border-primary/20 rounded-lg p-3 hover:bg-primary/10 transition-colors"
                >
                  <div className="flex justify-between items-start gap-2">
                    <p className="text-sm font-semibold text-foreground flex-1 break-words">{winner.name}</p>
                    <p className="text-sm font-bold text-primary whitespace-nowrap">#{winner.luckyNumber}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Ganhadores;
